// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVbSLSICpbEnEDMJBL4dcaresudBS7jt0',
    appId: '1:714039376752:web:fee912e1dc9d18e35fadb5',
    messagingSenderId: '714039376752',
    projectId: 'rewardsystem-4a36e',
    authDomain: 'rewardsystem-4a36e.firebaseapp.com',
    storageBucket: 'rewardsystem-4a36e.appspot.com',
    measurementId: 'G-51FLJ1QMM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgwsLj1BXTZbNcnFUkUH4zbuJn1wqX1Q',
    appId: '1:714039376752:android:cb0fab394c9eae595fadb5',
    messagingSenderId: '714039376752',
    projectId: 'rewardsystem-4a36e',
    storageBucket: 'rewardsystem-4a36e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTkfNjpTbH-UxCq0yN2UrOBaY5xUqy0QQ',
    appId: '1:714039376752:ios:bfff731abbc1c6665fadb5',
    messagingSenderId: '714039376752',
    projectId: 'rewardsystem-4a36e',
    storageBucket: 'rewardsystem-4a36e.appspot.com',
    iosClientId: '714039376752-egq1oc56cu3pcgi00a7oa41ncefsibbg.apps.googleusercontent.com',
    iosBundleId: 'com.co',
  );
}
